import type { Metadata } from 'next';
import './globals.css';
import { Exo_2 } from 'next/font/google';
import { cn } from '@/lib/utils';
import { Navbar } from '@/components/navigation';
import './globals.css';
import { NextIntlClientProvider } from 'next-intl';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const exo2 = Exo_2({ subsets: ['latin'], variable: '--font-exo-2' });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={cn('h-full', 'antialiased', exo2.variable)}
      suppressHydrationWarning>
      <body className='min-h-full flex flex-col'>
        <NextIntlClientProvider>
          <Navbar />
          <main> {children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
